global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "authservice"
    metrics_path: /metrics
    static_configs:
      - targets: ["authservice:8000"]

  - job_name: "casesservice"
    metrics_path: /metrics
    static_configs:
      - targets: ["casesservice:8000"]

  - job_name: "paymentservice"
    metrics_path: /metrics
    static_configs:
      - targets: ["paymentservice:8000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]