# Статические настройки Traefik
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    transport:
      respondingTimeouts:
        readTimeout: 0s
        writeTimeout: 0s
        idleTimeout: 0s

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic/services.yml
    watch: true

log:
  level: INFO
