/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FarmRouteImport } from './routes/farm'
import { Route as BalanceRouteImport } from './routes/balance'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUserNameRouteImport } from './routes/user/$userName'
import { Route as CasesCaseIdRouteImport } from './routes/cases/$caseId'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmRoute = FarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserNameRoute = UserUserNameRouteImport.update({
  id: '/$userName',
  path: '/$userName',
  getParentRoute: () => UserRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/farm': typeof FarmRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/admin': typeof ProtectedAdminRoute
  '/profile': typeof ProtectedProfileRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/user/$userName': typeof UserUserNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/farm': typeof FarmRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/admin': typeof ProtectedAdminRoute
  '/profile': typeof ProtectedProfileRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/user/$userName': typeof UserUserNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/balance': typeof BalanceRoute
  '/farm': typeof FarmRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/user/$userName': typeof UserUserNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balance'
    | '/farm'
    | '/login'
    | '/register'
    | '/user'
    | '/admin'
    | '/profile'
    | '/cases/$caseId'
    | '/user/$userName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balance'
    | '/farm'
    | '/login'
    | '/register'
    | '/user'
    | '/admin'
    | '/profile'
    | '/cases/$caseId'
    | '/user/$userName'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/balance'
    | '/farm'
    | '/login'
    | '/register'
    | '/user'
    | '/_protected/admin'
    | '/_protected/profile'
    | '/cases/$caseId'
    | '/user/$userName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  BalanceRoute: typeof BalanceRoute
  FarmRoute: typeof FarmRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UserRoute: typeof UserRouteWithChildren
  CasesCaseIdRoute: typeof CasesCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm': {
      id: '/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userName': {
      id: '/user/$userName'
      path: '/$userName'
      fullPath: '/user/$userName'
      preLoaderRoute: typeof UserUserNameRouteImport
      parentRoute: typeof UserRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface UserRouteChildren {
  UserUserNameRoute: typeof UserUserNameRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserUserNameRoute: UserUserNameRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  BalanceRoute: BalanceRoute,
  FarmRoute: FarmRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UserRoute: UserRouteWithChildren,
  CasesCaseIdRoute: CasesCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
