/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as BalanceRouteImport } from './routes/balance'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesCaseIdRouteImport } from './routes/cases/$caseId'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as CasesCaseIdOpenRouteImport } from './routes/cases/$caseId/open'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const CasesCaseIdOpenRoute = CasesCaseIdOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => CasesCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/cases': typeof CasesRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProtectedProfileRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/$caseId/open': typeof CasesCaseIdOpenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/cases': typeof CasesRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProtectedProfileRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/$caseId/open': typeof CasesCaseIdOpenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/balance': typeof BalanceRoute
  '/cases': typeof CasesRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/$caseId/open': typeof CasesCaseIdOpenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balance'
    | '/cases'
    | '/login'
    | '/profile'
    | '/cases/$caseId'
    | '/cases/$caseId/open'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balance'
    | '/cases'
    | '/login'
    | '/profile'
    | '/cases/$caseId'
    | '/cases/$caseId/open'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/balance'
    | '/cases'
    | '/login'
    | '/_protected/profile'
    | '/cases/$caseId'
    | '/cases/$caseId/open'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  BalanceRoute: typeof BalanceRoute
  CasesRoute: typeof CasesRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/cases/$caseId/open': {
      id: '/cases/$caseId/open'
      path: '/open'
      fullPath: '/cases/$caseId/open'
      preLoaderRoute: typeof CasesCaseIdOpenRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedProfileRoute: typeof ProtectedProfileRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedProfileRoute: ProtectedProfileRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface CasesCaseIdRouteChildren {
  CasesCaseIdOpenRoute: typeof CasesCaseIdOpenRoute
}

const CasesCaseIdRouteChildren: CasesCaseIdRouteChildren = {
  CasesCaseIdOpenRoute: CasesCaseIdOpenRoute,
}

const CasesCaseIdRouteWithChildren = CasesCaseIdRoute._addFileChildren(
  CasesCaseIdRouteChildren,
)

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRouteWithChildren
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRouteWithChildren,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  BalanceRoute: BalanceRoute,
  CasesRoute: CasesRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
