source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.10"
gem "jekyll-optional-front-matter", "~> 0.4"
gem "jekyll-relative-links", "~> 0.6"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
end
